name: Release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write # for pushing the sync-PR branch
  pull-requests: write # for creating/approving PRs

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - run: npm ci
        env:
          HUSKY: 0

      - run: npx semantic-release # semantic-release runs prepack before publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0

      - name: Open/Update sync PR (package.json + CHANGELOG.md)
        if: success()
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/sync-release-files # rolling PR
          title: 'chore: sync release files after publish'
          body: 'Files generated by semantic-release (version bump & changelog).'
          commit-message: 'chore(release): sync package.json & CHANGELOG.md'
          add-paths: |
            package.json
            package-lock.json
            CHANGELOG.md

      # auto-approve; requires repo settings "Allow GitHub Actions to create and approve pull requests"
      - name: Approve sync PR
        if: steps.cpr.outputs.pull-request-operation != 'none'
        uses: peter-evans/approve-pull-request@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          comment: 'Auto-approval for release file sync.'

      # enable auto-merge; requires repo setting “Allow auto-merge”
      - name: Enable auto-merge for sync PR
        if: steps.cpr.outputs.pull-request-operation != 'none'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
