name: Release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write # needed for tags + committing CHANGELOG/package.json

# Queue behavior: one release at a time per branch; newer runs wait.
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
        env:
          HUSKY: 0
      - run: npx semantic-release # semantic-release includes npm run prepack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
