name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run format

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test

  gate:
    name: gate
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: always()
    steps:
      - name: Fail if any dependency failed
        run: |
          echo "results=${{ join(needs.*.result, ',') }}"
          if echo "${{ join(needs.*.result, ',') }}" | grep -E '(failure|cancelled|skipped)'; then
            echo "Some required jobs did not succeed."
            exit 1
          fi
          echo "All required jobs passed."
