name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "linting..."

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "testing..."

  gate:
    name: gate
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - run: echo "All required jobs passed."
