name: Release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    # Skip runs on any chore commit (incl. the sync commit "chore(release): …")
    if: ${{ !(github.event_name == 'push' && (startsWith(github.event.head_commit.message, 'chore(') || startsWith(github.event.head_commit.message, 'chore:') || startsWith(github.event.head_commit.message, 'chore '))) }}
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - run: npm ci

      # semantic-release: publishes to npm, creates GH release, updates/creates CHANGELOG.md
      - name: Semantic Release
        id: sr
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Ensure the workspace has a diff for the sync PR:
      # persist the released version into package.json
      - name: Sync package.json version to released version
        if: steps.sr.outputs.new_release_published == 'true'
        run: |
          node -e "
            const fs = require('fs');
            const f = 'package.json';
            const j = JSON.parse(fs.readFileSync(f, 'utf8'));
            j.version = '${{ steps.sr.outputs.new_release_version }}';
            fs.writeFileSync(f, JSON.stringify(j, null, 2) + '\n');
          "

      # Refresh lockfile after bump so it's consistent with the new version field
      - name: Refresh lockfile after bump
        if: steps.sr.outputs.new_release_published == 'true'
        run: npm install --package-lock-only

      # Make sure no untracked temp files (e.g., previous runs) can interfere
      - name: Clean untracked files
        if: steps.sr.outputs.new_release_published == 'true'
        run: git clean -fdx

      # Don’t let hooks (e.g., Husky) mutate files during the PR commit
      - name: Disable git hooks (avoid Husky in PR commit)
        if: steps.sr.outputs.new_release_published == 'true'
        run: git config --global core.hooksPath /dev/null

      # Sanity: show what changed (useful if PR step no-ops)
      - name: Debug diff
        if: steps.sr.outputs.new_release_published == 'true'
        run: |
          git status
          git --no-pager diff --name-only

      - name: Open/Update sync PR (package.json + lockfile + CHANGELOG.md)
        if: steps.sr.outputs.new_release_published == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: chore/sync-release-files
          title: 'chore(release): v${{ steps.sr.outputs.new_release_version }}'
          commit-message: 'chore(release): v${{ steps.sr.outputs.new_release_version }}'
          body: |
            Files generated by semantic-release (version bump & changelog).

            ### Release notes for v${{ steps.sr.outputs.new_release_version }}

            ${{ steps.sr.outputs.new_release_notes }}
          add-paths: |
            package.json
            package-lock.json
            CHANGELOG.md
          committer: GitHub <noreply@github.com>
          author: GitHub Actions <actions@github.com>
          signoff: true
          delete-branch: true
          labels: |
            chore
            release

      # Surface what happened (helps diagnose "silent" runs)
      - name: Show PR step outputs
        if: steps.sr.outputs.new_release_published == 'true'
        run: |
          echo "operation=${{ steps.cpr.outputs.pull-request-operation }}"
          echo "number=${{ steps.cpr.outputs.pull-request-number }}"
          echo "url=${{ steps.cpr.outputs.pull-request-url }}"
