name: Release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: npm

      - run: npm ci
        env:
          HUSKY: 0

      # Run semantic-release: bumps version, updates CHANGELOG, publishes package
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0

      # Ensure package-lock.json reflects bumped version
      - name: Refresh lockfile after bump
        run: npm install --package-lock-only
        env:
          HUSKY: 0

      # Read bumped version from package.json (quote GITHUB_OUTPUT)
      - name: Read version
        id: ver
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # Extract the latest changelog section for PR body
      - name: Extract latest changelog section
        id: notes
        shell: bash
        run: |
          awk 'BEGIN{p=0} /^## /{ if(p) exit; p=1; next } p{print}' CHANGELOG.md > RELEASE_NOTES.md
          {
            echo "Files generated by semantic-release (version bump & changelog)."
            echo
            echo "### Release notes for v${{ steps.ver.outputs.version }}"
            echo
            cat RELEASE_NOTES.md
          } > PR_BODY.md

      # Open or update sync PR with version + changelog
      - name: Open/Update sync PR (package.json + CHANGELOG.md)
        if: success()
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/sync-release-files
          title: 'chore(release): v${{ steps.ver.outputs.version }}'
          commit-message: 'chore(release): v${{ steps.ver.outputs.version }}'
          body-path: PR_BODY.md
          add-paths: |
            package.json
            package-lock.json
            CHANGELOG.md

      # Enable auto-merge if repo settings allow
      - name: Enable auto-merge for sync PR
        if: steps.cpr.outputs.pull-request-operation != 'none'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
